#!/usr/bin/env bash
set -Eeuo pipefail

# Configure a container-local runtime environment for Claude Code, Codex,
# and the AMD LLM gateway proxy. This script is designed to run inside the
# ROCm dev container after scripts/setup-dev-env.sh.

LLM_GATEWAY_API_KEY="${LLM_GATEWAY_API_KEY:-${AMD_LLM_API_KEY:-}}"
LLM_GATEWAY_BASE_URL="${LLM_GATEWAY_BASE_URL:-${AMD_LLM_BASE_URL:-https://llm-api.amd.com}}"
LLM_GATEWAY_OPENAI_BASE_URL="${LLM_GATEWAY_OPENAI_BASE_URL:-}"
PROXY_HOST="${PROXY_HOST:-127.0.0.1}"
PROXY_PORT="${PROXY_PORT:-8082}"
RUNTIME_DIR="${RUNTIME_DIR:-$HOME/.amd-node-runtime}"
REPO_DIR="${AMD_NODE_RUNTIME_REPO:-/opt/amd-node-runtime}"

fail() {
  echo "[ERROR] $*" >&2
  exit 1
}

write_export() {
  local key="$1"
  local value="$2"
  printf 'export %s=%q\n' "$key" "$value"
}

if [[ -z "${LLM_GATEWAY_API_KEY}" ]]; then
  fail "LLM_GATEWAY_API_KEY is required"
fi

mkdir -p "${RUNTIME_DIR}" "$HOME/.codex"
chmod 700 "${RUNTIME_DIR}"
umask 077

{
  write_export AMD_LLM_API_KEY "${LLM_GATEWAY_API_KEY}"
  write_export AMD_LLM_BASE_URL "${LLM_GATEWAY_BASE_URL}"
  write_export PROXY_HOST "${PROXY_HOST}"
  write_export PROXY_PORT "${PROXY_PORT}"
} > "${RUNTIME_DIR}/amdproxy.env"

{
  write_export ANTHROPIC_BASE_URL "http://127.0.0.1:${PROXY_PORT}"
  write_export ANTHROPIC_AUTH_TOKEN "not-used"
  write_export ANTHROPIC_API_KEY "not-used"
  write_export DISABLE_PROMPT_CACHING "1"
} > "${RUNTIME_DIR}/claude-env.sh"

{
  echo "# Optional Codex API-key environment."
  echo "# Codex may still require 'codex login' depending on the exact release and account policy."
  write_export OPENAI_API_KEY "${LLM_GATEWAY_API_KEY}"
  if [[ -n "${LLM_GATEWAY_OPENAI_BASE_URL}" ]]; then
    write_export OPENAI_BASE_URL "${LLM_GATEWAY_OPENAI_BASE_URL}"
  else
    echo "# export OPENAI_BASE_URL=https://REPLACE_WITH_OPENAI_COMPATIBLE_GATEWAY/v1"
  fi
} > "${RUNTIME_DIR}/codex-env.sh"

{
  echo "# Auto-generated by amd-node-runtime. This file is node/container local."
  echo "[ -f \"${RUNTIME_DIR}/claude-env.sh\" ] && . \"${RUNTIME_DIR}/claude-env.sh\""
  echo "[ -f \"${RUNTIME_DIR}/codex-env.sh\" ] && . \"${RUNTIME_DIR}/codex-env.sh\""
} > "${RUNTIME_DIR}/env.sh"

chmod 600 "${RUNTIME_DIR}"/*.env "${RUNTIME_DIR}"/*.sh

if [[ -f "$HOME/.bashrc" ]] && ! grep -Fq "${RUNTIME_DIR}/env.sh" "$HOME/.bashrc"; then
  {
    echo ""
    echo "# amd-node-runtime agent/proxy env"
    echo "[ -f \"${RUNTIME_DIR}/env.sh\" ] && . \"${RUNTIME_DIR}/env.sh\""
  } >> "$HOME/.bashrc"
fi

if command -v tmux >/dev/null 2>&1; then
  if ! tmux has-session -t amdproxy 2>/dev/null; then
    tmux new-session -d -s amdproxy \
      "set -a; . '${RUNTIME_DIR}/amdproxy.env'; set +a; python3 '${REPO_DIR}/proxy/amd_proxy.py'"
  fi
fi

cat <<SUMMARY
Agent runtime configured.

Local env directory:
  ${RUNTIME_DIR}

Claude Code:
  source ${RUNTIME_DIR}/claude-env.sh
  claude

Codex:
  source ${RUNTIME_DIR}/codex-env.sh
  codex

AMDproxy:
  tmux attach -t amdproxy
  curl http://127.0.0.1:${PROXY_PORT}/health

GitHub auth remains manual:
  gh auth login
SUMMARY
