#!/usr/bin/env bash
set -Eeuo pipefail

# Configure the container-local runtime for Claude Code, Codex, and the two
# AMD gateway proxy sessions. This runs inside the ROCm dev container after
# scripts/setup-dev-env.sh.

LLM_GATEWAY_API_KEY="${LLM_GATEWAY_API_KEY:-${AMD_LLM_API_KEY:-}}"
LLM_GATEWAY_BASE_URL="${LLM_GATEWAY_BASE_URL:-${AMD_LLM_BASE_URL:-https://llm-api.amd.com}}"
LLM_GATEWAY_OPENAI_BASE_URL="${LLM_GATEWAY_OPENAI_BASE_URL:-${AMD_OPENAI_BASE_URL:-${LLM_GATEWAY_BASE_URL%/}/openai}}"

PROXY_HOST="${PROXY_HOST:-127.0.0.1}"
CLAUDE_PROXY_PORT="${CLAUDE_PROXY_PORT:-8082}"
CODEX_PROXY_PORT="${CODEX_PROXY_PORT:-8083}"

CLAUDE_MODEL="${CLAUDE_MODEL:-claude-opus-4-8}"
CLAUDE_EFFORT="${CLAUDE_EFFORT:-xhigh}"
CLAUDE_ULTRACODE="${CLAUDE_ULTRACODE:-1}"

CODEX_MODEL="${CODEX_MODEL:-gpt-5.5}"
CODEX_REASONING_EFFORT="${CODEX_REASONING_EFFORT:-xhigh}"
CODEX_REASONING_LABEL="${CODEX_REASONING_LABEL:-ultrahigh}"

RUNTIME_DIR="${RUNTIME_DIR:-$HOME/.amd-node-setup}"
RUNTIME_BIN_DIR="${RUNTIME_BIN_DIR:-${RUNTIME_DIR}/bin}"
REPO_DIR="${AMD_NODE_SETUP_REPO:-${AMD_NODE_RUNTIME_REPO:-/opt/amd-node-setup}}"

export PATH="$HOME/.local/bin:$PATH"

fail() {
  echo "[ERROR] $*" >&2
  exit 1
}

write_export() {
  local key="$1"
  local value="$2"
  printf 'export %s=%q\n' "$key" "$value"
}

find_real_bin() {
  local name="$1"
  local dir candidate
  IFS=: read -r -a path_parts <<< "${PATH}"
  for dir in "${path_parts[@]}"; do
    [[ -z "${dir}" ]] && dir="."
    [[ "${dir}" == "${RUNTIME_BIN_DIR}" ]] && continue
    candidate="${dir}/${name}"
    if [[ -x "${candidate}" ]]; then
      echo "${candidate}"
      return 0
    fi
  done
  return 1
}

append_once() {
  local file="$1"
  local needle="$2"
  local content="$3"
  if [[ -f "${file}" ]] && grep -Fq "${needle}" "${file}"; then
    return
  fi
  {
    echo ""
    echo "${content}"
  } >> "${file}"
}

start_tmux_session() {
  local session="$1"
  local env_file="$2"
  if ! command -v tmux >/dev/null 2>&1; then
    echo "[WARN] tmux is not installed; skipping ${session}" >&2
    return
  fi

  tmux kill-session -t "${session}" >/dev/null 2>&1 || true
  tmux new-session -d -s "${session}" \
    "set -a; . '${env_file}'; set +a; python3 '${REPO_DIR}/proxy/amd_proxy.py'"
}

write_codex_config() {
  local codex_config="$HOME/.codex/config.toml"
  mkdir -p "$HOME/.codex"
  chmod 700 "$HOME/.codex"

  if [[ -f "${codex_config}" ]] && ! grep -Fq "Auto-generated by amd-node-setup" "${codex_config}"; then
    cp -p "${codex_config}" "${codex_config}.bak.$(date +%Y%m%d%H%M%S)"
  fi

  {
    echo "# Auto-generated by amd-node-setup. This file is container local."
    echo "# Codex currently represents the requested ultrahigh setting as xhigh."
    printf 'model = "%s"\n' "${CODEX_MODEL}"
    echo 'model_provider = "amd_openai"'
    printf 'model_reasoning_effort = "%s"\n' "${CODEX_REASONING_EFFORT}"
    printf 'openai_base_url = "http://127.0.0.1:%s/v1"\n' "${CODEX_PROXY_PORT}"
    echo ""
    echo "[model_providers.amd_openai]"
    echo 'name = "AMD OpenAI Gateway"'
    printf 'base_url = "http://127.0.0.1:%s/v1"\n' "${CODEX_PROXY_PORT}"
    echo 'env_key = "OPENAI_API_KEY"'
    echo 'wire_api = "responses"'
    echo 'supports_websockets = false'
  } > "${codex_config}"
  chmod 600 "${codex_config}"
}

write_wrappers() {
  local real_claude=""
  local real_codex=""

  real_claude="$(find_real_bin claude || true)"
  real_codex="$(find_real_bin codex || true)"

  mkdir -p "${RUNTIME_BIN_DIR}"
  chmod 700 "${RUNTIME_DIR}" "${RUNTIME_BIN_DIR}"

  if [[ -n "${real_claude}" ]]; then
    {
      echo "#!/usr/bin/env bash"
      echo "set -Eeuo pipefail"
      printf '. %q\n' "${RUNTIME_DIR}/claude-env.sh"
      printf 'real_claude=%q\n' "${real_claude}"
      echo 'for arg in "$@"; do'
      echo '  case "${arg}" in'
      echo '    -h|--help|-v|--version) exec "${real_claude}" "$@" ;;'
      echo '  esac'
      echo 'done'
      echo 'if [[ "${CLAUDE_ULTRACODE:-1}" == "1" ]]; then'
      echo '  exec "${real_claude}" --settings '"'"'{"ultracode":true}'"'"' "$@"'
      echo "fi"
      echo 'exec "${real_claude}" "$@"'
    } > "${RUNTIME_BIN_DIR}/claude"
    chmod 700 "${RUNTIME_BIN_DIR}/claude"
  else
    echo "[WARN] claude binary not found; wrapper not written" >&2
  fi

  if [[ -n "${real_codex}" ]]; then
    {
      echo "#!/usr/bin/env bash"
      echo "set -Eeuo pipefail"
      printf '. %q\n' "${RUNTIME_DIR}/codex-env.sh"
      printf 'real_codex=%q\n' "${real_codex}"
      echo 'exec "${real_codex}" "$@"'
    } > "${RUNTIME_BIN_DIR}/codex"
    chmod 700 "${RUNTIME_BIN_DIR}/codex"
  else
    echo "[WARN] codex binary not found; wrapper not written" >&2
  fi
}

if [[ -z "${LLM_GATEWAY_API_KEY}" ]]; then
  fail "LLM_GATEWAY_API_KEY is required"
fi

mkdir -p "${RUNTIME_DIR}" "${RUNTIME_BIN_DIR}" "$HOME/.claude"
chmod 700 "${RUNTIME_DIR}" "${RUNTIME_BIN_DIR}" "$HOME/.claude"
umask 077

{
  write_export AMD_LLM_API_KEY "${LLM_GATEWAY_API_KEY}"
  write_export AMD_LLM_BASE_URL "${LLM_GATEWAY_BASE_URL}"
  write_export PROXY_HOST "${PROXY_HOST}"
  write_export PROXY_PORT "${CLAUDE_PROXY_PORT}"
  write_export PROXY_MODE "claude"
  write_export CLAUDE_DEFAULT_MODEL "${CLAUDE_MODEL}"
  write_export AMD_PROXY_MODELS "${CLAUDE_MODEL}"
} > "${RUNTIME_DIR}/amdproxy-claude.env"

{
  write_export AMD_LLM_API_KEY "${LLM_GATEWAY_API_KEY}"
  write_export AMD_LLM_BASE_URL "${LLM_GATEWAY_BASE_URL}"
  write_export PROXY_HOST "${PROXY_HOST}"
  write_export PROXY_PORT "${CODEX_PROXY_PORT}"
  write_export PROXY_MODE "openai"
  write_export OPENAI_UPSTREAM_BASE_URL "${LLM_GATEWAY_OPENAI_BASE_URL}"
  write_export CODEX_DEFAULT_MODEL "${CODEX_MODEL}"
  write_export CODEX_REASONING_EFFORT "${CODEX_REASONING_EFFORT}"
  write_export AMD_PROXY_MODELS "${CODEX_MODEL}"
} > "${RUNTIME_DIR}/amdproxy-codex.env"

{
  write_export ANTHROPIC_BASE_URL "http://127.0.0.1:${CLAUDE_PROXY_PORT}"
  write_export ANTHROPIC_AUTH_TOKEN "not-used"
  write_export ANTHROPIC_API_KEY "not-used"
  write_export ANTHROPIC_MODEL "${CLAUDE_MODEL}"
  write_export ANTHROPIC_DEFAULT_OPUS_MODEL "${CLAUDE_MODEL}"
  write_export ANTHROPIC_DEFAULT_OPUS_MODEL_NAME "Opus 4.8 via AMD Gateway"
  write_export ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION "AMD LLM Gateway pinned Opus 4.8"
  write_export ANTHROPIC_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES "effort,xhigh_effort,max_effort,thinking,adaptive_thinking,interleaved_thinking"
  write_export CLAUDE_CODE_EFFORT_LEVEL "${CLAUDE_EFFORT}"
  write_export CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY "1"
  write_export CLAUDE_ULTRACODE "${CLAUDE_ULTRACODE}"
  write_export DISABLE_PROMPT_CACHING "1"
} > "${RUNTIME_DIR}/claude-env.sh"

{
  write_export OPENAI_API_KEY "${LLM_GATEWAY_API_KEY}"
  write_export OPENAI_BASE_URL "http://127.0.0.1:${CODEX_PROXY_PORT}/v1"
  write_export CODEX_MODEL "${CODEX_MODEL}"
  write_export CODEX_REASONING_EFFORT "${CODEX_REASONING_EFFORT}"
  write_export CODEX_REASONING_LABEL "${CODEX_REASONING_LABEL}"
} > "${RUNTIME_DIR}/codex-env.sh"

{
  echo "# Auto-generated by amd-node-setup. This file is node/container local."
  echo "export PATH=\"${RUNTIME_BIN_DIR}:\$HOME/.local/bin:\$PATH\""
  echo "[ -f \"${RUNTIME_DIR}/claude-env.sh\" ] && . \"${RUNTIME_DIR}/claude-env.sh\""
  echo "[ -f \"${RUNTIME_DIR}/codex-env.sh\" ] && . \"${RUNTIME_DIR}/codex-env.sh\""
} > "${RUNTIME_DIR}/env.sh"

chmod 600 "${RUNTIME_DIR}"/*.env "${RUNTIME_DIR}"/*.sh
write_codex_config
write_wrappers

append_once \
  "$HOME/.bashrc" \
  "${RUNTIME_DIR}/env.sh" \
  "# amd-node-setup agent/proxy env
[ -f \"${RUNTIME_DIR}/env.sh\" ] && . \"${RUNTIME_DIR}/env.sh\""

start_tmux_session amdproxy-claude "${RUNTIME_DIR}/amdproxy-claude.env"
start_tmux_session amdproxy-codex "${RUNTIME_DIR}/amdproxy-codex.env"

cat <<SUMMARY
Agent runtime configured.

Local env directory:
  ${RUNTIME_DIR}

Proxy sessions:
  amdproxy-claude -> http://127.0.0.1:${CLAUDE_PROXY_PORT}  model=${CLAUDE_MODEL}  effort=ultracode/xhigh
  amdproxy-codex  -> http://127.0.0.1:${CODEX_PROXY_PORT}  model=${CODEX_MODEL}  effort=${CODEX_REASONING_LABEL}/${CODEX_REASONING_EFFORT}

Default commands after opening a new shell:
  claude
  codex

Health checks:
  curl http://127.0.0.1:${CLAUDE_PROXY_PORT}/health
  curl http://127.0.0.1:${CODEX_PROXY_PORT}/health

GitHub auth remains manual:
  gh auth login
SUMMARY
